### PR TITLE
Update createCanvas function for better performance

### PR DESCRIPTION
**Pull request by Roba1993**
I set up the performance about 100% by modifying the createCanvasAnd2dContext() function. The old function creates always a new canvas. My version reuse the canvas. This solution is still a bit hacky, but a lot better than the old solution. #5

### CODE REVIEW

**Comment by gre** [comment]
so it reuse a same canvas?
does this still work for multiple scenes? (e.g multiple "Lighting" instance)

Thanks

**Comment by Roba1993** [comment]
In my example yes. I have 2 lights and 4 objects and they all rendered correct. I used your hash function, to create a separate canvas for each light.

**Comment by gre** [comment]
Ok sounds good! thanks for the improvement.

I wish soon to drastically improve performance by moving to WebGL and maybe experimenting on top of Pixi.js. However that's is still speculative (and it is a much more complex world) but at least I need to give a try soon :-)

**Comment by Roba1993** [comment]
I would love the support you with that. As I sad, at the moment I make a game with PIXI.js and when your WebGL update is compatible whit that framework, I would love to use it.

**Pull request merged**
